[versions]
asm = "9.9"

[libraries]
findbugs = { module = "com.google.code.findbugs:jsr305", version = "3.0.2" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version = "26.0.2-1" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.42" }
brigadier = { module = "com.mojang:brigadier", version = "1.3.10" }
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }
reactorNetty = { module = "io.projectreactor.netty:reactor-netty-http", version = "1.3.0" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.17" }

junit-bom = { module = "org.junit:junit-bom", version = "5.14.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }

netty = { module = "io.netty:netty-all", version = "4.2.7.Final" }
netty-raknet = { module = "dev.kastle.netty:netty-transport-raknet", version = "1.3.0" }
netty-kcp = { module = "io.jpower.kcp:kcp-netty", version = "1.5.2" }

[bundles]
asm = ["asm", "asm-commons", "asm-tree", "asm-analysis"]
netty = ["netty", "netty-raknet", "netty-kcp"]

[plugins]
templateProcessor = { id = "net.lenni0451.template-processor", version = "1.0.1" }
